<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
class ThietBiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 
        DB::table('thietbi')->delete();
        DB::table('thietbi')->insert([
            [
                'TenThietBi' => 'Máy hút dịch Yuwell',
                'Model' => '7E-A',
                'Serial' => '00434',
                'MucDoRuiRo' => 'B', 
                'SoLuong' => '1',
                'DonViTinh' => 'Cái', 
                'TinhTrang' => 'Đã Thanh Lý', 
                'idNhomThietBi' => '',
                'idLoaiThietBi' => 'Máy hút dịch', 
                'idCanBoVatTuPhuTrach' => '20192914',
                'idCanBoKhoaPhongPhuTrach' => '', 
                'idKhoaPhongSuDung' => 'KHSTC', 
                'idNhaCungCap' => '',
                'idDonViBaoTri' => '', 
                'HangSanXuat' => 'Jiangsu yuyue',
                'XuatXu' => 'Trung quốc', 
                'NamSanXuat' => '2018', 
                'KiemDinhDinhKy' => '12 Tháng', 
                'NgayKiemDinhGanNhat' => Carbon::create('2000','01','01'),
                'NgayNhapKho' => Carbon::create('2021','02','11'), 
                'NgayHetHanBaoHanh' => Carbon::create('2000','01','01'), 
                'ThongSoKyThuat' => '', 
                'CauHinhKyThuat' => '', 
                'GiaTriBanDau' => '0',
                'KhauHaoHangNam' => '0', 
                'GiaTriHienTai' => '0', 
                'NamSuDung' => '2021',
                'GiaNhap' => '0',
            ],
            [
                'TenThietBi' => 'Bơm tiêm điện Terumo',
                'Model' => 'TE*SS700N03',
                'Serial' => '1703010872',
                'MucDoRuiRo' => 'B', 
                'SoLuong' => '1',
                'DonViTinh' => 'Cái', 
                'TinhTrang' => 'Đang Sử Dụng', 
                'idNhomThietBi' => '',
                'idLoaiThietBi' => 'Bơm tiêm điện', 
                'idCanBoVatTuPhuTrach' => '',
                'idCanBoKhoaPhongPhuTrach' => '', 
                'idKhoaPhongSuDung' => 'KHSTC', 
                'idNhaCungCap' => '',
                'idDonViBaoTri' => '', 
                'HangSanXuat' => 'Terumo',
                'XuatXu' => 'Nhật Bản', 
                'NamSanXuat' => '2017', 
                'KiemDinhDinhKy' => '12 Tháng', 
                'NgayKiemDinhGanNhat' => Carbon::create('2000','01','01'),
                'NgayNhapKho' => Carbon::create('2021','02','11'), 
                'NgayHetHanBaoHanh' => Carbon::create('2000','01','01'), 
                'ThongSoKyThuat' => '', 
                'CauHinhKyThuat' => '', 
                'GiaTriBanDau' => '0',
                'KhauHaoHangNam' => '0', 
                'GiaTriHienTai' => '0', 
                'NamSuDung' => '2021',
                'GiaNhap' => '0',
            ],
            [
                'TenThietBi' => 'Máy li tâm lạnh',
                'Model' => 'Z216MK',
                'Serial' => '61B2100088',
                'MucDoRuiRo' => 'B', 
                'SoLuong' => '1',
                'DonViTinh' => 'Cái', 
                'TinhTrang' => 'Đang Báo Hỏng', 
                'idNhomThietBi' => '',
                'idLoaiThietBi' => 'Máy ly tâm', 
                'idCanBoVatTuPhuTrach' => '20192914',
                'idCanBoKhoaPhongPhuTrach' => '', 
                'idKhoaPhongSuDung' => 'KVS', 
                'idNhaCungCap' => '',
                'idDonViBaoTri' => '', 
                'HangSanXuat' => 'HERMLE',
                'XuatXu' => 'Gemany', 
                'NamSanXuat' => '2021', 
                'KiemDinhDinhKy' => '12 Tháng', 
                'NgayKiemDinhGanNhat' => Carbon::create('2000','01','01'),
                'NgayNhapKho' => Carbon::create('2021','02','11'), 
                'NgayHetHanBaoHanh' => Carbon::create('2000','01','01'), 
                'ThongSoKyThuat' => '', 
                'CauHinhKyThuat' => '', 
                'GiaTriBanDau' => '0',
                'KhauHaoHangNam' => '0', 
                'GiaTriHienTai' => '0', 
                'NamSuDung' => '2021',
                'GiaNhap' => '0',
            ],
            [
                'TenThietBi' => 'Máy thận nhân tạo SURDIAL',
                'Model' => 'SURDIAL',
                'Serial' => '09T6606',
                'MucDoRuiRo' => '', 
                'SoLuong' => '1',
                'DonViTinh' => 'Cái', 
                'TinhTrang' => 'Đang Sửa Chữa', 
                'idNhomThietBi' => '',
                'idLoaiThietBi' => 'Máy thận nhân tạo', 
                'idCanBoVatTuPhuTrach' => '20192914',
                'idCanBoKhoaPhongPhuTrach' => '', 
                'idKhoaPhongSuDung' => 'KLM', 
                'idNhaCungCap' => '',
                'idDonViBaoTri' => '', 
                'HangSanXuat' => 'Nipro',
                'XuatXu' => 'Nhật Bản', 
                'NamSanXuat' => '2009', 
                'KiemDinhDinhKy' => '', 
                'NgayKiemDinhGanNhat' => Carbon::create('2000','01','01'),
                'NgayNhapKho' => Carbon::create('2021','02','11'), 
                'NgayHetHanBaoHanh' => Carbon::create('2000','01','01'), 
                'ThongSoKyThuat' => '', 
                'CauHinhKyThuat' => '', 
                'GiaTriBanDau' => '0',
                'KhauHaoHangNam' => '0', 
                'GiaTriHienTai' => '0', 
                'NamSuDung' => '2009',
                'GiaNhap' => '0',
            ],
            [
                'TenThietBi' => 'Máy ép tim',
                'Model' => '7501-002',
                'Serial' => 'B2090',
                'MucDoRuiRo' => '', 
                'SoLuong' => '1',
                'GiaNhap' => '0',
                'DonViTinh' => 'Cái', 
                'TinhTrang' => 'Ngừng Sử Dụng', 
                'idNhomThietBi' => '',
                'idLoaiThietBi' => 'Hệ thống/ Thiết bị hồi sức khác', 
                'idCanBoVatTuPhuTrach' => '20192914',
                'idCanBoKhoaPhongPhuTrach' => '', 
                'idKhoaPhongSuDung' => 'KCC', 
                'idNhaCungCap' => '',
                'idDonViBaoTri' => '', 
                'HangSanXuat' => 'KONTRON',
                'XuatXu' => 'Pháp', 
                'NamSanXuat' => '2009', 
                'KiemDinhDinhKy' => '', 
                'NgayKiemDinhGanNhat' => Carbon::create('2000','01','01'),
                'NgayNhapKho' => Carbon::create('2021','02','11'), 
                'NgayHetHanBaoHanh' => Carbon::create('2000','01','01'), 
                'ThongSoKyThuat' => '', 
                'CauHinhKyThuat' => '', 
                'GiaTriBanDau' => '0',
                'KhauHaoHangNam' => '0', 
                'GiaTriHienTai' => '0', 
                'NamSuDung' => '2009',
            ],
        ]);
    }
}
